# Assignment 3 - Data Preprocessing

This assignment will be focused on data preprocessing methods that you've seen in class. We will be using the scikit-learn library. Some sample codes will be provided, but the goal is definitely for you to explore different functions and possibilities. Therefore, do not hesitate to go wild and stretch the capabilities of these libraries. 
In addition, we will be using the Random Forest Classifier. Do not worry if you do not know what this classifier is. It will be covered in the following classes!

*Don't forget that commenting your code is very important!*

### 1. Import packages 

###### Import the packages you think will be useful. We have imported some packages for you already, as they are outside the scope of this lecture. 

*Note*: we presented some example packages during class (eg. numpy, matplotlib, etc.). However, we only focus on the end results, so you can use any libraries of you choice.

In [2]:
# IMPORT PACKAGES
from sklearn.ensemble import RandomForestClassifier

# =========== YOUR CODE HERE ======== 

import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

### 2. Get started with the machine learning. 

For this assignment, we will be using the kickstarter dataset from <a>kaggle.com</a>. Kickstarter is a famous online platform for entreneurs to advertise and raise money for their new startup projects. This dataset compiles the success, goal and other informations of the projects in 2018. 

We will try to use this dataset to predict the whether or not a project would succeed. We will be using the **'state'** column as out target labels.

###### 1) Read the dataset './dataset/kickstarter.csv'.

In [20]:
# =========== YOUR CODE HERE ======== 
ds = pd.read_csv('./dataset/kickstarter.csv')
#ds = ds.drop(columns='name')
#ds = ds.drop(columns = 'currency')
#ds = ds.drop(columns = 'ID')
#ds = ds.fillna(ds['usd pledged'].mean())
ds.isna().any()

ID                  False
name                 True
category            False
main_category       False
currency            False
deadline            False
goal                False
launched            False
pledged             False
state               False
backers             False
country             False
usd pledged          True
usd_pledged_real    False
usd_goal_real       False
dtype: bool

###### 2) Describe the dataset. What do you see?

### <span style="background-color: #F9F2EB"> Your dataset description here: ...  </span>

###### 3) Create your train and test sets using a 0.8/0.2 split with the `train_test_split`  function from sciki-learn. 
Name your final datasets as `X_train`, `Y_train`, `X_test` and `Y_test`.

*Note: There are many ways of splitting data. A sample code for train-test splitting using *masks* is provided.*

In [4]:
# Random mask to split train / test sets. 
msk = np.random.rand(len(ds)) < 0.8 
train = ds[msk]
test = ds[~msk]

Y_train = train['state']
X_train = train.drop(columns='state')


Y_test = test['state']
X_test = test.drop(columns='state')

# Examine the size of the datasets to make sure that the split ratio was properly applied. (0.8/0.2)
print('Number of samples in train set: ', len(X_train))
print('Number of samples in test set: ', len(X_test))

Number of samples in train set:  302930
Number of samples in test set:  75731

In [23]:
# SCIKIT-LEARN TRAIN-TEST SPLIT
# =========== YOUR CODE HERE ======== 
Y = ds['state']
X = ds.drop(columns='state')
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)


 # get dummy = one hot
    

# Examine the size of the datasets to make sure that the split ratio was properly applied. (0.8/0.2)
print('Number of samples in train set: ', len(X_train))
print('Number of samples in test set: ', len(X_test))

Number of samples in train set:  302928
Number of samples in test set:  75733

###### 4) Fit the dataset onto the random forest classifer. 
Once again, do not worry about the what the classifier entails. We will cover this in more details in the following classes.

In [18]:
#enc = OneHotEncoder(handle_unknown='error')

#X_train = enc.fit(X_train)
randomForest = RandomForestClassifier()

# =========== YOUR CODE HERE ======== 
randomForest.fit(X_train, Y_train)

/Users/stevenchan/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

### UH OH!

As you may see, the dataset is not ready to be fit onto the algorithm just yet. There is some preprocessing to do before you can do anything with it. The machine does not quite understand the data yet. While you're at it, you can also play around to see how you can preprocess the data to enhance the model performance too!

Things that you can consider doing include, but not limited to: 
- Encode categorical data to machine intepretable 
- Normalize your data 
- Select / drop columns
- Take care of missing values 
- etc.

###### 5) Preprocess your data the way you want, but make it work!

In [ ]:
# =========== YOUR CODE HERE ========

In [26]:
# Make a copy of the dataset because you never want to overwrite the original one! 
processed_ds = ds.copy()

* **Missing values**

In [27]:
# Check which row as missing values.
processed_ds.isna().any()

ID                  False
name                 True
category            False
main_category       False
currency            False
deadline            False
goal                False
launched            False
pledged             False
state               False
backers             False
country             False
usd pledged          True
usd_pledged_real    False
usd_goal_real       False
dtype: bool

In [32]:
# Fill 'usd pledged' missing values with those from 'usd_pledged_real', 
# assuming they are similar from examing the other rows.
'''processed_ds['usd pledged'] = processed_ds.apply(
    lambda row: row['usd_pledged_real'] if np.isnan(row['usd pledged']) else row['usd pledged'],
    axis=1)'''
processed_ds['usd pledged'] = processed_ds.fillna(processed_ds['usd pledged'].mean())

In [33]:
# Fill 'name' missing values with 'no name'
processed_ds['name'] = processed_ds['name'].fillna(value='no name')

In [42]:
# Verify that we have handled all the missing values. 
processed_ds.isna().any()

category            False
main_category       False
currency            False
deadline            False
goal                False
launched            False
pledged             False
state               False
backers             False
country             False
usd pledged         False
usd_pledged_real    False
usd_goal_real       False
dtype: bool

* **Dropping columns**

In [35]:
# Drop ID and name. These columns don't seem to give relevant information to the success of the project.
processed_ds = processed_ds.drop(columns=['ID', 'name'])
processed_ds

,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,1000002330,0.00,1533.95
1,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,1000003930,2421.00,30000.00
2,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.00,failed,3,US,1000004038,220.00,45000.00
3,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.00,failed,1,US,1000007540,1.00,5000.00
4,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.00,canceled,14,US,1000011046,1283.00,19500.00
5,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26 13:38:27,52375.00,successful,224,US,1000014025,52375.00,50000.00
6,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1000023410,1205.00,1000.00
7,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01 20:05:12,453.00,failed,40,US,1000030581,453.00,25000.00
8,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24 18:14:43,8233.00,canceled,58,US,1000034518,8233.00,125000.00
9,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11 21:55:48,6240.57,canceled,43,US,100004195,6240.57,65000.00
10,Nonfiction,Publishing,CAD,2013-10-09,2500.0,2013-09-09 18:19:37,0.00,failed,0,CA,100004721,0.00,2406.39
11,Indie Rock,Music,USD,2013-04-08,12500.0,2013-03-09 06:42:58,12700.00,successful,100,US,100005484,12700.00,12500.00
12,Crafts,Crafts,USD,2014-10-02,5000.0,2014-09-02 17:11:50,0.00,failed,0,US,1000055792,0.00,5000.00
13,Games,Games,USD,2016-03-25,200000.0,2016-02-09 23:01:12,0.00,failed,0,US,1000056157,0.00,200000.00
14,Tabletop Games,Games,GBP,2017-05-03,5000.0,2017-04-05 19:44:18,94175.00,successful,761,GB,1000057089,121857.33,6469.73
15,Design,Design,USD,2015-02-28,2500.0,2015-01-29 02:10:53,664.00,failed,11,US,1000064368,664.00,2500.00
16,Comic Books,Comics,USD,2014-11-08,1500.0,2014-10-09 22:27:52,395.00,failed,16,US,1000064918,395.00,1500.00
17,Art Books,Publishing,USD,2015-05-10,3000.0,2015-04-10 21:20:54,789.00,failed,20,US,1000068480,789.00,3000.00
18,Music,Music,USD,2012-08-17,250.0,2012-08-02 14:11:32,250.00,successful,7,US,1000070642,250.00,250.00
19,Food,Food,USD,2012-06-02,5000.0,2012-05-03 17:24:32,1781.00,failed,40,US,1000071625,1781.00,5000.00
20,Fashion,Fashion,USD,2013-12-30,20000.0,2013-11-25 07:06:11,34268.00,successful,624,US,1000072011,34268.00,20000.00
21,Childrenswear,Fashion,AUD,2017-09-07,2500.0,2017-08-08 01:20:20,1.00,failed,1,AU,1000081649,0.81,2026.10
22,Theater,Theater,USD,2014-06-15,3500.0,2014-05-16 10:10:38,650.00,failed,12,US,1000082254,650.00,3500.00
23,Drinks,Food,NOK,2015-02-25,500.0,2015-01-26 19:17:33,48.00,failed,3,NO,1000087442,6.29,65.55
24,Comics,Comics,USD,2014-11-12,175.0,2014-10-23 17:15:50,701.66,successful,66,US,1000091520,701.66,175.00
25,Music,Music,USD,2011-01-06,10000.0,2010-12-07 23:16:50,15827.00,successful,147,US,1000102741,15827.00,10000.00
26,DIY,Crafts,GBP,2016-01-05,12000.0,2015-12-06 20:09:06,0.00,failed,0,GB,1000103948,0.00,17489.65
27,Webseries,Film & Video,CAD,2014-12-14,17757.0,2014-11-14 18:02:00,48905.00,successful,571,CA,1000104688,42174.03,15313.04
28,Comics,Comics,GBP,2016-01-28,100.0,2015-12-29 16:59:29,112.38,successful,27,GB,1000104953,160.60,142.91
29,Animation,Film & Video,USD,2017-05-03,50000.0,2017-04-03 17:11:33,57577.31,successful,840,US,100011318,57577.31,50000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
378631,Playing Cards,Games,USD,2014-10-03,10000.0,2014-09-03 19:53:50,13861.50,successful,413,US,999832803,13861.50,10000.00
378632,Comedy,Film & Video,USD,2014-06-05,12000.0,2014-05-06 23:50:34,0.00,failed,0,US,99984851,0.00,12000.00
378633,Apparel,Fashion,USD,2014-12-13,25000.0,2014-11-13 17:16:17,11643.00,failed,97,US,999865831,11643.00,25000.00
378634,Photography,Photography,USD,2011-01-08,4000.0,2010-11-08 02:43:59,3531.00,failed,37,US,999867839,3531.00,4000.00
378635,Nonfiction,Publishing,USD,2015-09-24,800.0,2015-08-25 22:37:14,70.00,failed,5,US,99987261,70.00,800.00
378636,Country & Folk,Music,CAD,2014-12-17,5000.0,2014-11-17 17:50:12,5435.00,successful,78,CA,999877902,4686.96,4311.83
378637,Shorts,Film & Video,USD,2017-10-13,10000.0,2017-08-29 06:57:28,10245.00,successful,123,US,999878813,10245.00,10000.00
378638,Nonfiction,Publishing,USD,2014-08-15,5000.0,2014-07-15 02:10:39,18.00,failed,5,US,999880710,18.00,5000.00
378639,Drinks,Food,USD,2015-12-03,5000.0,2015-11-03 13:04:14,5579.00,successful,103,US,999884445,5579.00,5000.00
378640,Fiction,Publishing,USD,2014-09-11,1000.0,2014-08-08 21:49:31,100.00,canceled,2,US,999893629,100.00,1000.00
378641,Product Design,Design,CHF,2015-09-04,80000.0,2015-07-06 18:00:47,0.00,failed,0,CH,99991751,0.00,82207.27
378642,Tabletop Games,Games,EUR,2017-10-31,1000.0,2017-10-04 11:26:44,1246.00,successful,35,FR,999929142,1452.47,1165.70
378643,3D Printing,Technology,USD,2014-05-26,6500.0,2014-05-05 20:22:45,0.00,canceled,0,US,999931480,0.00,6500.00
378644,Product Design,Design,USD,2015-12-15,3500.0,2015-11-23 07:33:14,6169.00,successful,120,US,999934908,6169.00,3500.00
378645,Comics,Comics,GBP,2013-10-10,16000.0,2013-09-10 22:45:26,2738.00,failed,38,GB,999941823,4374.99,25566.05
378646,Children's Books,Publishing,USD,2013-11-30,950.0,2013-10-18 21:35:04,1732.02,successful,31,US,999943841,1732.02,950.00
378647,Nonfiction,Publishing,USD,2012-09-14,4999.0,2012-08-15 17:11:00,980.00,failed,16,US,999950812,980.00,4999.00
378648,Tabletop Games,Games,USD,2016-02-23,500.0,2016-01-24 16:03:27,121.00,canceled,5,US,999955533,121.00,500.00
378649,Narrative Film,Film & Video,USD,2017-04-09,500.0,2017-02-08 02:28:44,135.00,failed,6,US,999963618,135.00,500.00
378650,Apps,Technology,USD,2016-09-05,6000.0,2016-07-29 15:36:29,0.00,failed,0,US,99996661,0.00,6000.00
378651,Classical Music,Music,CAD,2014-03-22,5000.0,2014-02-20 01:00:16,5501.00,successful,78,CA,999969812,4983.69,4529.81
378652,Documentary,Film & Video,NOK,2015-04-28,20000.0,2015-03-29 21:30:33,21500.00,successful,36,NO,999971898,2875.83,2675.19
378653,Documentary,Film & Video,USD,2012-03-16,1700.0,2012-02-15 04:31:10,25.00,failed,1,US,999972264,25.00,1700.00
378654,Small Batch,Food,USD,2017-04-19,6500.0,2017-03-20 22:08:22,154.00,failed,4,US,999975836,154.00,6500.00
378655,Poetry,Publishing,CAD,2014-09-20,5500.0,2014-08-06 03:46:07,0.00,canceled,0,CA,999976312,0.00,4949.60
378656,Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.00,canceled,1,US,999976400,25.00,50000.00
378657,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.00,failed,5,US,999977640,155.00,1500.00
378658,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.00,failed,1,US,999986353,20.00,15000.00
378659,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.00,failed,6,US,999987933,200.00,15000.00
378660,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.00,failed,17,US,999988282,524.00,2000.00

* **Encode categorical data.**
Machines do not understand words (strings). You must encode the data into numbers.

In [36]:
# Look at the columns datatypes and see which columns need to be taken care of. 
processed_ds.dtypes

category             object
main_category        object
currency             object
deadline             object
goal                float64
launched             object
pledged             float64
state                object
backers               int64
country              object
usd pledged          object
usd_pledged_real    float64
usd_goal_real       float64
dtype: object

In [37]:
# Convert 'category', 'main_category', 'currency', 'country' into numerical categorical codes 
processed_ds['category'] = processed_ds["category"].astype('category').cat.codes
processed_ds['main_category'] = processed_ds["main_category"].astype('category').cat.codes
processed_ds['currency'] = processed_ds["currency"].astype('category').cat.codes
processed_ds['country'] = processed_ds["country"].astype('category').cat.codes

In [38]:
# Examine the dataset to see if the encoding have been applied properly. 
processed_ds.head()

,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,108,12,5,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,9,1000002330,0.0,1533.95
1,93,6,13,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,22,1000003930,2421.0,30000.00
2,93,6,13,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,22,1000004038,220.0,45000.00
3,90,10,13,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,22,1000007540,1.0,5000.00
4,55,6,13,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,22,1000011046,1283.0,19500.00

In [39]:
# 'launched' and 'deadline' hold dates. This is not categorical therefore label encoding wouldn't work. 
# We chose to keep the year of the date for simplicity purposes. 
processed_ds['launched'] = pd.to_datetime(processed_ds['launched']).dt.year
processed_ds['deadline'] = pd.to_datetime(processed_ds['deadline']).dt.year

In [40]:
# Verify that all columns now hold numerical values. 
processed_ds.dtypes

category              int16
main_category          int8
currency               int8
deadline              int64
goal                float64
launched              int64
pledged             float64
state                object
backers               int64
country                int8
usd pledged          object
usd_pledged_real    float64
usd_goal_real       float64
dtype: object

###### 6) Refit your processed dataset onto the classifier. Test your model on your test set and print out the accuracy. 
If everything goes well, you should get an accuracy of around 0.85~0.88

In [1]:


# Random mask to split train / test sets. 
msk = np.random.rand(len(processed_ds)) < 0.8 
train = processed_ds[msk]
test = processed_ds[~msk]

Y_train = train['state']
X_train = train.drop(columns='state')

Y_test = test['state']
X_test = test.drop(columns='state')

randomForest.fit(X_train, Y_train)
prediction = randomForest.predict(X_test)
print('Accuracy: ',accuracy_score(prediction, Y_test))

NameError: name 'np' is not defined

###### 7) What other preprocessing techniques can you use to improve performance? Refer for documentation here for other preprocessing techniques [https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing]